name: Makefile CI

on:
  push:
    branches: [ "CI/CD" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Mensaje
      run: echo "hola mundo"

    - name: Checkout del código fuente
      uses: actions/checkout@v3
      
    - name: Python setup
      uses: actions/setup-python@v3
      with:
          python-version: '3'
    - name: Python req
      run: pip3 install setuptools
    - name: Python wheel
      run: pip install wheel

    - name: Python req txt
      run: |
        pip3 install -r requirements.txt

    - name: Python run
      run: python3 rqmemat.py
      
    - name: Make
      run: make

    - name: Run test
      run: ./simulate
