name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Mensaje
      run: echo "hola mundo"

    - name: Listar
      run: pwd
      
    - name: Make
      run: make Makefile

    - name: Run test
      run: ./simulate
