name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Mensaje
      run: echo "hola mundo"

    - name: Checkout del código fuente
      uses: actions/checkout@v3
      
    - name: Python setup
      uses: actions/setup-python@v3
      with:
          python-version: '3.X'
    - name: Python req
      run: pipreqs rqmemat.py  
      
    - name: Make
      run: make

    - name: Run test
      run: ./simulate
