name: NPPES

on:
  push:
    branches:
    - main
    - feature/network
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del c贸digo fuente
        uses: actions/checkout@v3
      
      - name: Python setup
        uses: actions/setup-python@v3
        with:
          python-version: '3'
      
      - name: Install dependencies
        run: |
          pip3 install setuptools
          pip3 install wheel
          pip3 install numpy
          pip3 install sympy
          pip3 install tabulate

  compile:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout del c贸digo fuente
        uses: actions/checkout@v3

      - name: Make
        run: make

  python-executions:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout del c贸digo fuente
        uses: actions/checkout@v3

      - name: Run Python scripts
        run: |
          python3 rqmemat.py  > matrix.txt
          python3 coefgen.py > coef.txt

  run-simulation:
    runs-on: ubuntu-latest
    needs: python-executions
    steps:
      - name: Checkout del c贸digo fuente
        uses: actions/checkout@v3

      - name: Run simulation
        run: ./simulate
