name: NPPES CI

on:
  push:
    branches:
    - main
    - feature/network
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Mensaje
      run: echo "hola mundo"

    - name: Checkout del código fuente
      uses: actions/checkout@v3
      
    - name: Python setup
      uses: actions/setup-python@v3
      with:
          python-version: '3'
    - name: Install dependencies
      run: |
        pip3 install setuptools
        pip3 install wheel
        pip3 install numpy
        pip3 install sympy
        pip3 install tabulate

    - name: Make
      run: make

    - name: Persistir artefactos
      uses: actions/upload-artifact@v2
      with:
        name: setup-artifacts
        path: matrix.txt
        path: coef.txt

  test:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v3

    - name: Descargar artefactos
      uses: actions/download-artifact@v2
      with:
        name: setup-artifacts

    - name: Run test
      run: ./simulate
